# Generated by Django 4.0.2 on 2022-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registerer_dttm', models.DateTimeField(auto_now_add=True, verbose_name='동록시간')),
            ],
            options={
                'verbose_name': '패스트캠퍼스 사용자',
                'verbose_name_plural': '패스크캠퍼스 사용자',
                'db_table': 'fastcampus_fcuser',
            },
        ),
    ]
