# Generated by Django 4.0.2 on 2022-02-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='registerer_dttm',
            new_name='registered_dttm',
        ),
    ]
